spring:
  application:
    name: springboottest
  mandatory-file-encoding: utf-8
  http:
    encoding:
      charset: utf-8
      enabled: true

server:
  port: 9090

#自定义配置
myConfig:
  myObject:
    myName: zhangsan
    myAge: 30



